<?php return array (
  '118fdfde37c297ec2ed0f94aacc94456' => 
  array (
    'criteria' => 
    array (
      'pagetitle' => 'Home',
    ),
    'object' => 
    array (
      'id' => 1,
      'type' => 'document',
      'contentType' => 'text/html',
      'pagetitle' => 'Home',
      'longtitle' => '',
      'description' => '',
      'alias' => 'index',
      'link_attributes' => '',
      'published' => 1,
      'pub_date' => 0,
      'unpub_date' => 0,
      'parent' => 0,
      'isfolder' => 0,
      'introtext' => NULL,
      'content' => '',
      'richtext' => 1,
      'template' => 1,
      'menuindex' => 0,
      'searchable' => 1,
      'cacheable' => 1,
      'createdby' => 1,
      'createdon' => 1373554686,
      'editedby' => 0,
      'editedon' => 0,
      'deleted' => 0,
      'deletedon' => 0,
      'deletedby' => 0,
      'publishedon' => 0,
      'publishedby' => 0,
      'menutitle' => '',
      'donthit' => 0,
      'privateweb' => 0,
      'privatemgr' => 0,
      'content_dispo' => 0,
      'hidemenu' => 0,
      'class_key' => 'modDocument',
      'context_key' => 'web',
      'content_type' => 1,
      'uri' => NULL,
      'uri_override' => 0,
      'hide_children_in_tree' => 0,
      'show_in_tree' => 1,
      'properties' => NULL,
    ),
  ),
);